### ISSUE TITLE
changing lang forces change of currency

### ISSUE THREAD

**Issue by egils-verkstad** [bashrc/fin#14]
did:
$ cat ~/.fin/settings.txt
Default Account: current
Default Currency: SEK
Default VAT rate: 0
Server: 
Date Format: %d/%m/%Y
Språk: swedish
Tema: normal
$ fin lang "English uk"
Language changed to english uk
$ cat .fin/settings.txt 
Default Account: current
Default Currency: GBP
Default VAT rate: 20
Server: 
Date Format: %d/%m/%Y
Language: english uk
Theme: normal

Is this intentional?

**Comment by bashrc** [comment]
I think so, but you can change the currency subsequently
